dependencies:
- name: gitlab
  version: 1.3.4
  repository: https://charts.gitlab.io/
- name: metallb
  version: 0.8.3
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: grafana
  version: 1.21.2
  repository: https://kubernetes-charts.storage.googleapis.com/