apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  labels:
    app: certmanager-issuer
  name: gitlab-review-app-issuer
spec:
  acme:
    email: {{ .Values.gitlab.certmanager-issuer.email }}
    http01: {}
    privateKeySecretRef:
      name: gitlab-acme-key
    server: https://acme-v02.api.letsencrypt.org/directory
