apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cluster-issuer-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: certmanager-issuer
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  resource.yml: |
    apiVersion: certmanager.k8s.io/v1alpha1
    kind: ClusterIssuer
    metadata:
      labels:
        app: certmanager-issuer
      name: {{ .Release.Name }}-cluster-issuer
      namespace: {{ .Release.Namespace }}
    spec:
      acme:
        email: {{ .Values.acme.email }}
        # server: https://acme-v02.api.letsencrypt.org/directory
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
          name: gitlab-acme-key
        http01: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cluster-issuer
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: certmanager-issuer
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backoffLimit: 5
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name }}-issuer-job-pod
        image: rancher/hyperkube:v1.11.1-rancher1
        command:
        - kubectl
        - apply
        - -f
        - /etc/config/resource.yml
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: {{ .Release.Name }}-cluster-issuer-config
      restartPolicy: Never