apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Name }}
  name: metallb-config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - {{ .Values.gitlab.global.hosts.externalIP }}/32
